# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import idm_pb2 as idm__pb2


class AuthenticationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/idm.AuthenticationService/Register',
                request_serializer=idm__pb2.RegisterRequest.SerializeToString,
                response_deserializer=idm__pb2.RegisterResponse.FromString,
                )
        self.GetUsers = channel.unary_unary(
                '/idm.AuthenticationService/GetUsers',
                request_serializer=idm__pb2.UsersRequest.SerializeToString,
                response_deserializer=idm__pb2.UsersResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/idm.AuthenticationService/Delete',
                request_serializer=idm__pb2.DeleteRequest.SerializeToString,
                response_deserializer=idm__pb2.DeleteResponse.FromString,
                )
        self.Authenticate = channel.unary_unary(
                '/idm.AuthenticationService/Authenticate',
                request_serializer=idm__pb2.AuthenticationRequest.SerializeToString,
                response_deserializer=idm__pb2.AuthenticationResponse.FromString,
                )
        self.ValidateJWT = channel.unary_unary(
                '/idm.AuthenticationService/ValidateJWT',
                request_serializer=idm__pb2.ValidateJWTRequest.SerializeToString,
                response_deserializer=idm__pb2.ValidateJWTResponse.FromString,
                )
        self.InvalidateJWT = channel.unary_unary(
                '/idm.AuthenticationService/InvalidateJWT',
                request_serializer=idm__pb2.InvalidateJWTRequest.SerializeToString,
                response_deserializer=idm__pb2.InvalidateJWTResponse.FromString,
                )
        self.ChangePassword = channel.unary_unary(
                '/idm.AuthenticationService/ChangePassword',
                request_serializer=idm__pb2.ChangePasswordRequest.SerializeToString,
                response_deserializer=idm__pb2.ChangePasswordResponse.FromString,
                )


class AuthenticationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateJWT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateJWT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangePassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=idm__pb2.RegisterRequest.FromString,
                    response_serializer=idm__pb2.RegisterResponse.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=idm__pb2.UsersRequest.FromString,
                    response_serializer=idm__pb2.UsersResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=idm__pb2.DeleteRequest.FromString,
                    response_serializer=idm__pb2.DeleteResponse.SerializeToString,
            ),
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=idm__pb2.AuthenticationRequest.FromString,
                    response_serializer=idm__pb2.AuthenticationResponse.SerializeToString,
            ),
            'ValidateJWT': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateJWT,
                    request_deserializer=idm__pb2.ValidateJWTRequest.FromString,
                    response_serializer=idm__pb2.ValidateJWTResponse.SerializeToString,
            ),
            'InvalidateJWT': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateJWT,
                    request_deserializer=idm__pb2.InvalidateJWTRequest.FromString,
                    response_serializer=idm__pb2.InvalidateJWTResponse.SerializeToString,
            ),
            'ChangePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangePassword,
                    request_deserializer=idm__pb2.ChangePasswordRequest.FromString,
                    response_serializer=idm__pb2.ChangePasswordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'idm.AuthenticationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthenticationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.AuthenticationService/Register',
            idm__pb2.RegisterRequest.SerializeToString,
            idm__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.AuthenticationService/GetUsers',
            idm__pb2.UsersRequest.SerializeToString,
            idm__pb2.UsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.AuthenticationService/Delete',
            idm__pb2.DeleteRequest.SerializeToString,
            idm__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.AuthenticationService/Authenticate',
            idm__pb2.AuthenticationRequest.SerializeToString,
            idm__pb2.AuthenticationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateJWT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.AuthenticationService/ValidateJWT',
            idm__pb2.ValidateJWTRequest.SerializeToString,
            idm__pb2.ValidateJWTResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InvalidateJWT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.AuthenticationService/InvalidateJWT',
            idm__pb2.InvalidateJWTRequest.SerializeToString,
            idm__pb2.InvalidateJWTResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.AuthenticationService/ChangePassword',
            idm__pb2.ChangePasswordRequest.SerializeToString,
            idm__pb2.ChangePasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
